version: "3"
services:
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/
  nonebot:
    build: .
    container_name: nonebot
    ports:
      - "20000:20000" # 映射端口到宿主机 宿主机端口:容器端口
    network_mode: bridge
    restart: unless-stopped