CONSOLE_BASE_URL = "/capi"

CONSOLE_AUTH_URL = CONSOLE_BASE_URL + "/auth"

CONSOLE_RUNTIME_INFO_URL = CONSOLE_BASE_URL + "/runtime"
CONSOLE_MESSAGE_INFO_URL = CONSOLE_BASE_URL + "/message"

CONSOLE_SERVICE_BASE_URL = CONSOLE_BASE_URL + "/service"
CONSOLE_SERVICE_LIST_URL = CONSOLE_SERVICE_BASE_URL + "/list"
CONSOLE_SERVICE_EDIT_URL = CONSOLE_SERVICE_BASE_URL + "/edit"

CONSOLE_BLOCK_BASE_URL = CONSOLE_BASE_URL + "/block"
CONSOLE_BLOCK_LIST_URL = CONSOLE_BLOCK_BASE_URL + "/list"
CONSOLE_BLOCK_EDIT_URL = CONSOLE_BLOCK_BASE_URL + "/edit"
